# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric loader (common across versions)
loader_version=0.19.5

# Mod Properties
mod_version=1.0.0
maven_group=dev.rcvmod
archives_base_name=rcv
mod_id=rcv
mod_name=RCV
